# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

components:
  - ../../../components/gke/resources/tpu/v5e-2x4

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
  - path: job.patch.yaml
    target:
      kind: Job
