apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: gemma-2b-vllm-inference-server
  name: gemma-2b-vllm-deployment
spec:
  selector:
    matchLabels:
      app: gemma-2b-vllm-inference-server
  template:
    metadata:
      labels:
        app: gemma-2b-vllm-inference-server
        ai.gke.io/model: gemma-2b
    spec:
      containers:
      - name: inference-server
        env:
          - name: MODEL_ID
            value: google/gemma-2b
