# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

components:
  - ../../../../components/policies/resources/gpu/1-L4

patches:
  - path: deployment.patch.yaml
    target:
      kind: Deployment
    options:
      allowNameChange: true
  - path: service.patch.yaml
    target:
      kind: Service
    options:
      allowNameChange: true
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --tensor-parallel-size=1
