apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: singlehost-inference-hpa
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric:
        name: vllm-token-latency-ms
      target:
        type: AverageValue
